version: '2'
services:

  e2e_selenium:
    build: e2e_selenium
    container_name: e2e_selenium
    volumes:
      - ./e2e_selenium/e2e:/app
    working_dir: /app
    privileged: true


  core:
    build: backend
    container_name:
      core
    volumes:
      - ./backend/deployments:/opt/jboss/wildfly/standalone/deployments
    entrypoint: ["wait-for-container-end.sh", "-c", "liquibase", "--", "/start-server.sh"]
    depends_on:
      - db
    ports:
      - '90:8080'
    environment:
      TZ: Europe/Warsaw
      APP_ENVIRONMENT: development
      APP_DB_HOST: db

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    container_name: frontend


  db:
    extends:
      file: backend/database/docker-compose.yml
      service: db
    container_name:
      db

  liquibase:
    extends:
      file: backend/database/docker-compose.yml
      service: liquibase
    container_name:
      liquibase

  core_compiler:
    extends:
      file: backend/docker-compose.override.yml
      service: core_compiler
    container_name:
      core_compiler


volumes:
  # For Liquibase container.
  maven_liquibase: {}
  deployments: {}
  maven_core_compiler: {}


