version: '2'
services:
  
  frontend:
    image: teracy/angular-cli:1.0.0
    volumes:
      - ./:/app
    container_name:
      frontend
    working_dir: /app
    command: npm install
    command: ng serve host=0.0.0.0
    
  core:
    build: backend
    container_name:
      core
    volumes:
      - ./backend/deployments:/opt/jboss/wildfly/standalone/deployments
    entrypoint: ["wait-for-container-end.sh", "-c", "liquibase", "--", "/start-server.sh"]
    depends_on:
      - db
    environment:
      TZ: Europe/Warsaw
      APP_ENVIRONMENT: development
      APP_DB_HOST: db

  db:
    extends:
      file: backend/database/docker-compose.yml
      service: db
    container_name:
      db
  
  liquibase:
    extends:
      file: backend/database/docker-compose.yml
      service: liquibase
    container_name:
      liquibase
    
  core_compiler:
    build: backend/compiler
    volumes:
      - ./backend:/app
      - ./backend/maven_core_compiler:/root/.m2
    container_name:
      core_compiler
  

volumes:
  # For Liquibase container.
  maven_liquibase: {}
  deployments: {}
  maven_core_compiler: {}


